language: java
jdk:
- oraclejdk8
services:
- docker
script:
- mvn clean jacoco:prepare-agent install sonar:sonar
after_success:
- bash <(curl -s https://codecov.io/bash)
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker build -t $DOCKER_IMAGE .;
  docker tag $DOCKER_IMAGE $DOCKER_IMAGE:$DOCKER_TAG;
  docker push $DOCKER_IMAGE;
  fi
addons:
  sonarcloud:
    organization: codenergic
    token:
      secure: C/bwhQsjwpKg7qaw5ZPvrlsNZ1YCS4HJxvH/VmQmtyskm333Dc6md4ZttcGc68Uepvh6SSBmOp9oGy2Z2tOQzgiyLBgRiC1BJb8KHAHReNiAgCbwldL4tstPZqGUa6bpcap5b5xLEyMN5O2V3D+uuXBGd/QMsC88a5ECeXqh2mz9lWLcACeOPSleT5Hk/SKB51j6Ri4gCIeRhKIlYgTbE54wYyKV/l1dZ+7dcsohfZmTgCSxXnzuNg9LlHFO1/zOUztNtW17P4yH8WwZDVoQfGvOFgxRwRYF90dFdw9a7nVHVseXMZUz/0olu60isbI/HCAarRFzpDORKsMYJpXfGlQQFtJSLzK64STEKGroryLf4JYwwrkL7SUxw434UH7h6JTDhatB0g4v0jhql07316o8HrqcMh614oyXW+ww3IPyyZ3ILNCezb+qJSWeM1w3ettabX4KvbUzdFVQivn2WKuVPpO6oCo2GmRwlcp2RnDv9fnY+rTWN8ukQ2tvhD9rXmGTJ7PydzKEW9Ju56XetcPUJdzLGFrsSG5/TccEtVaqBFKk3i9h5DIXtqRkw6/Ja0I2X8nKgnBWtqW/xOSpmuLcqH2ktfkDGD2oQCPUdwn3Mb2zfmhQOlUrAhegibZNu99lWLW2hEvhoOFJKKjn5dHQtcbElzXTRQ7zCb/kQk0=
env:
  global:
  - DOCKER_IMAGE=codenergic/theskeleton
  - DOCKER_TAG=0.12.0
